[versions]
agp = "8.5.0"
circleimageview = "3.1.0"
constraintlayout = "2.1.3"
firebaseAuth = "21.0.1"
firebaseBom = "33.1.1"
firebaseCore = "17.2.1"
firebaseDatabase = "20.0.3"
firebaseMessaging = "24.0.0"
firebaseStorage = "21.0.0"
glide = "4.12.0"
junit = "4.13.2"
junitVersion = "1.2.0"
espressoCore = "3.6.0"
appcompat = "1.7.0"
material = "1.12.0"
playServicesAuth = "20.0.1"
activity = "1.8.0"
navigationFragment = "2.6.0"
navigationUi = "2.6.0"

[libraries]
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebaseCore" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabase" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
firebase-storage = { module = "com.google.firebase:firebase-storage", version.ref = "firebaseStorage" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

